# Generated by Django 3.2 on 2024-10-25 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plataforma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tipo', models.CharField(max_length=50)),
                ('Generacio', models.CharField(max_length=50)),
                ('Almacenamiento', models.CharField(max_length=50)),
                ('Fabricante', models.CharField(max_length=50)),
                ('Precio', models.CharField(max_length=50)),
            ],
        ),
    ]
