# Generated by Django 3.2 on 2024-10-25 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PlataformaApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plataforma',
            old_name='Generacio',
            new_name='Generacion',
        ),
    ]
