# Generated by Django 3.2 on 2024-10-25 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PlataformaApp', '0002_rename_generacio_plataforma_generacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plataforma',
            old_name='Almacenamiento',
            new_name='almacenamiento',
        ),
        migrations.RenameField(
            model_name='plataforma',
            old_name='Fabricante',
            new_name='fabricante',
        ),
        migrations.RenameField(
            model_name='plataforma',
            old_name='Generacion',
            new_name='generacion',
        ),
        migrations.RenameField(
            model_name='plataforma',
            old_name='Precio',
            new_name='precio',
        ),
        migrations.RenameField(
            model_name='plataforma',
            old_name='Tipo',
            new_name='tipo',
        ),
    ]
