# Generated by Django 3.2 on 2024-10-25 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlataformaApp', '0003_auto_20241024_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plataforma',
            name='almacenamiento',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='plataforma',
            name='precio',
            field=models.FloatField(),
        ),
    ]
